name: C++ Build for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure and Build Project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run Tests (optional)
      run: |
        ./build/tqccs  # Run the compiled binary
